# Generated by Django 4.0.1 on 2022-01-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travail_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix_text', models.CharField(max_length=200)),
                ('nbre_place', models.IntegerField(default=0)),
                ('travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.travail')),
            ],
        ),
    ]
