# Generated by Django 4.0 on 2022-01-03 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_debut', models.DateField()),
                ('date_de_fin', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('lieux', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField()),
                ('nom', models.CharField(max_length=200)),
                ('lieux', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('adresse', models.CharField(max_length=50)),
                ('nationalite', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('metier', models.CharField(choices=[('developpeur', 'dev Android'), ('developpeur', 'DEV WEb'), ('DATA SCIENTIST', 'DATA SCIENTIST')], max_length=200)),
                ('cv', models.FileField(upload_to='Cv_doc', verbose_name='User_Cv')),
                ('competences', models.ManyToManyField(related_name='competences_user', to='core.Competence')),
                ('experiences', models.ManyToManyField(related_name='experiences_user', to='core.Experience')),
                ('formations', models.ManyToManyField(related_name='formation_user', to='core.Formation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilRetruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('adresse', models.CharField(max_length=50)),
                ('nationalite', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_contrat', models.CharField(max_length=50)),
                ('salaire', models.PositiveIntegerField()),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('description', models.TextField()),
                ('Job_statue', models.CharField(choices=[('wait', 'en attente'), ('bad', 'refuser'), ('poster', 'ok')], max_length=150)),
                ('competences', models.ManyToManyField(related_name='competences_job', to='core.Competence')),
                ('experiences', models.ManyToManyField(related_name='experiences_job', to='core.Experience')),
                ('formations', models.ManyToManyField(related_name='formation_job', to='core.Formation')),
            ],
        ),
    ]
