# Generated by Django 4.0 on 2022-01-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_debut',
            new_name='date_de_debut',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='date_fin',
            new_name='date_de_fin',
        ),
    ]
