# Generated by Django 4.0 on 2022-01-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_date_debut_job_date_de_debut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_de_debut',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='date_de_fin',
            new_name='date_fin',
        ),
    ]
