# Generated by Django 4.0 on 2022-01-10 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_job_job_statue_alter_postuler_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuler',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
