# Generated by Django 4.0 on 2022-01-03 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_date_de_debut_job_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='domaine',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='nombres_experiences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='postuler',
            field=models.ManyToManyField(to='core.ProfilUser'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salaire',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
