# Generated by Django 4.0 on 2022-01-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_postuler_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_debut',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='type_contrat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_location',
            field=models.CharField(max_length=200),
        ),
    ]
